FROM centos:7.7.1908
LABEL maintainer="massimo.groppelli@zucchetti.it"

RUN rpm -Uvh https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
RUN yum install -y postgresql11-server postgresql11 postgresql11-contrib

